# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamovimentacao',
            options={'ordering': ('-dt_atualizacao',), 'verbose_name': 'Agenda Movimentacao', 'verbose_name_plural': 'Agendas Movimentacao'},
        ),
    ]
